### ISSUE TITLE
string to stream browser version

### ISSUE THREAD

**Issue by nicky508** [rdf-ext/rdf-parser-jsonld#6]
How to use the string-to-stream lib in a browser version? In the example a require is used for this.

**Comment by l00mi** [comment]
With the help of https://www.npmjs.com/package/browserify you can bundle the require include in one js file.

index.js
```
global.rdf-parser-jsonld = require("rdf-parser-jsonlod")
```

Then just `browserify index.js > bundle.js`, include bundle.js in your html and voilà you got rdf-parser-jsonld as a global.

**Comment by nicky508** [comment]
Used browserify and followed your steps:

SyntaxError: Assigning to rvalue (2:0) while parsing

**Comment by l00mi** [comment]
Okay, can you a tiny bit more specific where this happens?

**Comment by nicky508** [comment]
On: browserify index.js bundle.js

index.js

`global.rdf-parser-jsonld = require("rdf-parser-jsonld")`

```
SyntaxError: Assigning to rvalue (2:0) while parsing C:\xampp\htdocs\nfirs_report\js\index.js while parsing file: C:\xampp\htdocs\nfirs_report\js\index.js
    at DestroyableTransform.end [as _flush] (C:\Users\Nicky\AppData\Roaming\npm\node_modules\browserify\node_modules\insert-module-globals\index.js:96:21)
    at DestroyableTransform.<anonymous> (C:\Users\Nicky\AppData\Roaming\npm\node_modules\browserify\node_modules\readable-stream\lib\_stream_transform.js:138:49)
    at DestroyableTransform.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at prefinish (C:\Users\Nicky\AppData\Roaming\npm\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:596:14)
    at finishMaybe (C:\Users\Nicky\AppData\Roaming\npm\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:604:5)
    at endWritable (C:\Users\Nicky\AppData\Roaming\npm\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:615:3)
    at DestroyableTransform.Writable.end (C:\Users\Nicky\AppData\Roaming\npm\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:571:41)
    at DestroyableTransform.onend (C:\Users\Nicky\AppData\Roaming\npm\node_modules\browserify\node_modules\readable-stream\lib\_stream_readable.js:570:10)

```

**Comment by l00mi** [comment]
its `browserify index.js > bundle.js`

two things, please try to understand what browserify does, and probably you might do yourself a favor switching to a posix OS for such development. (might be just a linux in a VM)

**Comment by nicky508** [comment]
Makes no difference between: `browserify index.js bundle.js` and `browserify index.js > bundle.js`. Will try it on a linux machine.

**Comment by l00mi** [comment]
Ah, and also have a look at http://rdf-ext.zazuko.com/ might be the easier solution here.
(Sorry that I did not think about this earlier.)
